### ISSUE TITLE
## 시장조사하기

### ISSUE THREAD

**Issue by zdx456** [zdx456/SemiProject-1#1]
- [x] 분야 정하기
- [x] 롤모델 사이트 찾기
- [x] 관리자 기능을 무료로 이용할 수 있는 사이트 찾기

**Comment by zdx456** [comment]
분야별 롤모델 사이트 : https://www.justwatch.com/kr

**Comment by zdx456** [comment]
분야별 롤모델 사이트 : https://m.kinolights.com/  ,https://tvnng.com/(뭔가 부족함)

**Comment by Daybreak53** [comment]
분야별 롤모델 사이트 (영문) : 
https://www.ottplay.com/
https://ottwatchlist.com/

영문 사이트이지만 UI도 깔끔하고 참고가 될 것 같습니다.

**Comment by songhyeondo** [comment]
부트스트랩 기반 관리자 템플릿 
https://blog.uhoon.co.kr/entry/%EB%B6%80%EC%8A%A4%ED%8A%B8%ED%8A%B8%EB%9E%A9-%EA%B8%B0%EB%B0%98-%EB%AC%B4%EB%A3%8C-%EA%B4%80%EB%A6%AC%EC%9E%90-%ED%85%9C%ED%94%8C%EB%A6%BF-20%EC%84%A0-2017

**Comment by songhyeondo** [comment]
관리자 기능 체험
https://yslab.kr/93

**Comment by songhyeondo** [comment]
[여러개중 클릭해서 보기]
https://www.google.com/search?q=%EC%98%81%ED%99%94+erd&newwindow=1&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjS2Jyd9eD2AhXKfd4KHX70C4MQ_AUoAXoECAEQAw&biw=1920&bih=1007&dpr=1

[괜찮아보이는것]
https://velog.io/@ssmin0606/%EC%98%81%ED%99%94-%EC%B6%94%EC%B2%9C-%EC%82%AC%EC%9D%B4%ED%8A%B8-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-4.-ERD-%EC%84%A4%EA%B3%84

**Comment by zdx456** [comment]
주제 선정은 완료 된걸로 진행 하겠습니다!
