### ISSUE TITLE
Flow Chart 작성

### ISSUE THREAD

**Issue by zdx456** [zdx456/SemiProject-1#12]
- [x] Client 페이지 작성
- [x] error 페이지 작성
- [x] review 페이지 작성
- [x] contents 페이지 작성
- [x] admin 페이지 작성

**Comment by zdx456** [comment]
https://app.diagrams.net/#Hzdx456%2FSemiProject-1%2Fmain%2Fsemi-1.drawio
 작성중

**Comment by minyugyeong** [comment]
게시판 플로우 차트 semi-min.drawio 파일에 추가하였고, ERD에도 게시판 테이블 추가하였습니다.
수정사항 말씀해주시면 반영하겠습니다.

(조장님 drawio 파일은 제가 직접적으로 수정할 수 없게 되어있어서 제 파일에다 했습니다ㅠㅠ)

**Comment by zdx456** [comment]
https://app.diagrams.net/#Hzdx456%2FSemiProject-1%2Fmain%2Fsemi-1.drawio

관리자 페이지, 게시판 플로우차트 수정 5/1
