### ISSUE TITLE
화면 만들기

### ISSUE THREAD

**Issue by zdx456** [zdx456/SemiProject-1#16]
******

* 관리자 페이지
컨텐츠 관리, 등록 , 회원 관리 등
***
* 컨텐츠 페이지
검색 페이지 , 영화 상세 페이지 등
***
* 회원 페이지
로그인, 회원가입, 선호장르, 가입중인 OTT 등
***
* 고객센터 페이지
고객센터 개시판, 1:1문의 등
***
* 메인페이지
정렬(평균 편점, 관심컨텐츠, 최신순[비동기]) 등
***
- [x] 초안 생성하기
- [x] 예상 화면 구현하기 (Figma)

**Comment by Daybreak53** [comment]
작성 완료된 화면 설계 초안 (22.04.29 회의 내용)
[화면 초안.pdf](https://github.com/zdx456/SemiProject-1/files/8598293/default.pdf)

**Comment by reeyuna** [comment]
설계 초안을 바탕으로 각 페이지별로 UI Design 구현 완료 (2022.04.29 회의 후 작성 완료)
[UI Design.pdf](https://github.com/zdx456/SemiProject-1/files/8598921/UI.Design.pdf)
