### ISSUE TITLE
담당자

### ISSUE THREAD

**Issue by zdx456** [zdx456/SemiProject-1#17]
-------
***

- 회원 1명

- [x] 송현도
**** 
- 컨텐츠/리뷰 2명

- [x] 유성현
- [x] 이유나
**** 
- 관리자 2명

- [x] 이기주
- [x] 민유경
**** 
- 고객센터 1명

- [x] 천지연

**Comment by zdx456** [comment]
각자 이름에 체크하시고 확인 댓글 달아 주세요!

**Comment by zdx456** [comment]
https://github.com/zdx456/SemiProject-1/projects/6#column-18584520

**Comment by zdx456** [comment]
확인하였습니다.

**Comment by minyugyeong** [comment]
확인했습니다.

**Comment by Daybreak53** [comment]
확인했습니다.

**Comment by GIGIJU** [comment]
확인했습니다~

**Comment by reeyuna** [comment]
확인하였습니다!

**Comment by songhyeondo** [comment]
확인이용~
